//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeetingRecorder {
    using System;


    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        public Resources() {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MeetingRecorder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }

        public static string Idle {
            get {
                return ResourceManager.GetString("Idle", resourceCulture);
            }
        }

        public static string Recording {
            get {
                return ResourceManager.GetString("Recording", resourceCulture);
            }
        }

        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }

        public static string StatusDetecting {
            get {
                return ResourceManager.GetString("StatusDetecting", resourceCulture);
            }
        }

        public static string StatusUnknown {
            get {
                return ResourceManager.GetString("StatusUnknown", resourceCulture);
            }
        }

        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }

        public static string HeaderTitle {
            get {
                return ResourceManager.GetString("HeaderTitle", resourceCulture);
            }
        }

        public static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }

        public static string StatusLabel {
            get {
                return ResourceManager.GetString("StatusLabel", resourceCulture);
            }
        }

        public static string OutputFormatLabel {
            get {
                return ResourceManager.GetString("OutputFormatLabel", resourceCulture);
            }
        }

        public static string StartMonitoring {
            get {
                return ResourceManager.GetString("StartMonitoring", resourceCulture);
            }
        }

        public static string StopMonitoring {
            get {
                return ResourceManager.GetString("StopMonitoring", resourceCulture);
            }
        }

        public static string StopRecording {
            get {
                return ResourceManager.GetString("StopRecording", resourceCulture);
            }
        }

        public static string OpenFolder {
            get {
                return ResourceManager.GetString("OpenFolder", resourceCulture);
            }
        }

        public static string ShowStatusWindow {
            get {
                return ResourceManager.GetString("ShowStatusWindow", resourceCulture);
            }
        }

        public static string RecordingsFolder {
            get {
                return ResourceManager.GetString("RecordingsFolder", resourceCulture);
            }
        }

        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }

        public static string UiLanguageLabel {
            get {
                return ResourceManager.GetString("UiLanguageLabel", resourceCulture);
            }
        }

        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }

        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }

        public static string SelectFolderDescription {
            get {
                return ResourceManager.GetString("SelectFolderDescription", resourceCulture);
            }
        }

        public static string SelectValidFolder {
            get {
                return ResourceManager.GetString("SelectValidFolder", resourceCulture);
            }
        }

        public static string GoogleDriveSection {
            get {
                return ResourceManager.GetString("GoogleDriveSection", resourceCulture);
            }
        }

        public static string GoogleClientIdLabel {
            get {
                return ResourceManager.GetString("GoogleClientIdLabel", resourceCulture);
            }
        }

        public static string GoogleClientSecretLabel {
            get {
                return ResourceManager.GetString("GoogleClientSecretLabel", resourceCulture);
            }
        }

        public static string ClearTokenButton {
            get {
                return ResourceManager.GetString("ClearTokenButton", resourceCulture);
            }
        }

        public static string TokenClearedMessage {
            get {
                return ResourceManager.GetString("TokenClearedMessage", resourceCulture);
            }
        }

        public static string GoogleDriveFolderPathLabel {
            get {
                return ResourceManager.GetString("GoogleDriveFolderPathLabel", resourceCulture);
            }
        }

        public static string GoogleDriveFolderPathPlaceholder {
            get {
                return ResourceManager.GetString("GoogleDriveFolderPathPlaceholder", resourceCulture);
            }
        }

        public static string GoogleDriveEnabledLabel {
            get {
                return ResourceManager.GetString("GoogleDriveEnabledLabel", resourceCulture);
            }
        }

        public static string GoogleDriveStatusLabel {
            get {
                return ResourceManager.GetString("GoogleDriveStatusLabel", resourceCulture);
            }
        }

        public static string GoogleDriveStatusChecking {
            get {
                return ResourceManager.GetString("GoogleDriveStatusChecking", resourceCulture);
            }
        }

        public static string GoogleDriveNotSignedIn {
            get {
                return ResourceManager.GetString("GoogleDriveNotSignedIn", resourceCulture);
            }
        }

        public static string GoogleDriveSignedIn {
            get {
                return ResourceManager.GetString("GoogleDriveSignedIn", resourceCulture);
            }
        }

        public static string GoogleDriveSignedInAs {
            get {
                return ResourceManager.GetString("GoogleDriveSignedInAs", resourceCulture);
            }
        }

        public static string GoogleDriveSignInButton {
            get {
                return ResourceManager.GetString("GoogleDriveSignInButton", resourceCulture);
            }
        }

        public static string GoogleDriveSigningIn {
            get {
                return ResourceManager.GetString("GoogleDriveSigningIn", resourceCulture);
            }
        }

        public static string GoogleDriveLoginSuccess {
            get {
                return ResourceManager.GetString("GoogleDriveLoginSuccess", resourceCulture);
            }
        }

        public static string GoogleDriveLoginFailed {
            get {
                return ResourceManager.GetString("GoogleDriveLoginFailed", resourceCulture);
            }
        }

        public static string UploadFailed {
            get {
                return ResourceManager.GetString("UploadFailed", resourceCulture);
            }
        }

        public static string UploadedToCloud {
            get {
                return ResourceManager.GetString("UploadedToCloud", resourceCulture);
            }
        }

        public static string UploadToDrive {
            get {
                return ResourceManager.GetString("UploadToDrive", resourceCulture);
            }
        }

        public static string UploadingFile {
            get {
                return ResourceManager.GetString("UploadingFile", resourceCulture);
            }
        }

        public static string UploadSucceeded {
            get {
                return ResourceManager.GetString("UploadSucceeded", resourceCulture);
            }
        }

        public static string ThemeLabel {
            get {
                return ResourceManager.GetString("ThemeLabel", resourceCulture);
            }
        }

        public static string ThemeSystem {
            get {
                return ResourceManager.GetString("ThemeSystem", resourceCulture);
            }
        }

        public static string ThemeLight {
            get {
                return ResourceManager.GetString("ThemeLight", resourceCulture);
            }
        }

        public static string ThemeDark {
            get {
                return ResourceManager.GetString("ThemeDark", resourceCulture);
            }
        }

        public static string StartWithWindowsLabel {
            get {
                return ResourceManager.GetString("StartWithWindowsLabel", resourceCulture);
            }
        }

        public static string AutoCheckUpdatesLabel {
            get {
                return ResourceManager.GetString("AutoCheckUpdatesLabel", resourceCulture);
            }
        }

        public static string CheckForUpdates {
            get {
                return ResourceManager.GetString("CheckForUpdates", resourceCulture);
            }
        }

        public static string UpdateAvailableTitle {
            get {
                return ResourceManager.GetString("UpdateAvailableTitle", resourceCulture);
            }
        }

        public static string UpdateAvailableHeader {
            get {
                return ResourceManager.GetString("UpdateAvailableHeader", resourceCulture);
            }
        }

        public static string UpdateAvailableDescription {
            get {
                return ResourceManager.GetString("UpdateAvailableDescription", resourceCulture);
            }
        }

        public static string CurrentVersionLabel {
            get {
                return ResourceManager.GetString("CurrentVersionLabel", resourceCulture);
            }
        }

        public static string NewVersionLabel {
            get {
                return ResourceManager.GetString("NewVersionLabel", resourceCulture);
            }
        }

        public static string UpdateNow {
            get {
                return ResourceManager.GetString("UpdateNow", resourceCulture);
            }
        }

        public static string Later {
            get {
                return ResourceManager.GetString("Later", resourceCulture);
            }
        }

        public static string SkipVersion {
            get {
                return ResourceManager.GetString("SkipVersion", resourceCulture);
            }
        }

        public static string DownloadingUpdate {
            get {
                return ResourceManager.GetString("DownloadingUpdate", resourceCulture);
            }
        }

        public static string ExtractingUpdate {
            get {
                return ResourceManager.GetString("ExtractingUpdate", resourceCulture);
            }
        }

        public static string UpdateFailed {
            get {
                return ResourceManager.GetString("UpdateFailed", resourceCulture);
            }
        }

        public static string UpToDate {
            get {
                return ResourceManager.GetString("UpToDate", resourceCulture);
            }
        }

        public static string CheckingForUpdates {
            get {
                return ResourceManager.GetString("CheckingForUpdates", resourceCulture);
            }
        }

        public static string ReleaseNotesLabel {
            get {
                return ResourceManager.GetString("ReleaseNotesLabel", resourceCulture);
            }
        }

        public static string OrganizeFilesButton {
            get {
                return ResourceManager.GetString("OrganizeFilesButton", resourceCulture);
            }
        }

        public static string OrganizeSuccess {
            get {
                return ResourceManager.GetString("OrganizeSuccess", resourceCulture);
            }
        }

        public static string OrganizeFailed {
            get {
                return ResourceManager.GetString("OrganizeFailed", resourceCulture);
            }
        }

        public static string TabGeneral {
            get {
                return ResourceManager.GetString("TabGeneral", resourceCulture);
            }
        }

        public static string TabRecording {
            get {
                return ResourceManager.GetString("TabRecording", resourceCulture);
            }
        }

        public static string TabGoogleDrive {
            get {
                return ResourceManager.GetString("TabGoogleDrive", resourceCulture);
            }
        }

        public static string MinFileSizeLabel {
            get {
                return ResourceManager.GetString("MinFileSizeLabel", resourceCulture);
            }
        }

        public static string MinFileSizeTooltip {
            get {
                return ResourceManager.GetString("MinFileSizeTooltip", resourceCulture);
            }
        }

        public static string RecordingSettings {
            get {
                return ResourceManager.GetString("RecordingSettings", resourceCulture);
            }
        }

        public static string GeneralSettings {
            get {
                return ResourceManager.GetString("GeneralSettings", resourceCulture);
            }
        }
    }
}
